### ISSUE TITLE
CI tests are being skipped

### ISSUE THREAD

**Issue by igoumiri** [LLNL/MuyGPyS#150]
I noticed that tests passed on my draft PR https://github.com/LLNL/MuyGPyS/pull/145 whereas I explicitly pushed a broken test. It looks like everything runs fine but the actual tests are skipped.

I think the cause is that the test action uses a mix of `test-group` https://github.com/LLNL/MuyGPyS/blob/f3ce6075b2bf64b8881153a4fe80a0c76e796c2f/.github/workflows/develop-test.yml#L17

and `test_group` https://github.com/LLNL/MuyGPyS/blob/f3ce6075b2bf64b8881153a4fe80a0c76e796c2f/.github/workflows/develop-test.yml#L36

**Comment by bwpriest** [comment]
good catch. I'm not sure how we didn't notice this earlier.

**Comment by bwpriest** [comment]
Thanks for fixing this Imène! Fixed with #151.
