### ISSUE TITLE
Pip install broken on develop

### ISSUE THREAD

**Issue by igoumiri** [LLNL/MuyGPyS#233]
I tried to install the `develop` branch via `pip` with
```shell
pip install "muygpys[hnswlib,jax_cpu] @ git+https://github.com/LLNL/MuyGPyS.git@develop#egg=muygpys"
```
and the install looked successful but was actually broken. It wouldn't let me import anything from MuyGPyS.

I was able to install at commit `1156bb3076a76c73198a10ee47166d647e131334` instead so it's very likely a problem with https://github.com/LLNL/MuyGPyS/pull/231.

**Comment by bwpriest** [comment]
This was due to an issue with the new build system. This is fixed in #242 and in the new release.
